const HTTP_OK_STATUS = 200;
const HTTP_CREATED_STATUS = 201;
const HTTP_BAD_REQUST_STATUS = 400;
const HTTP_UNAUTHORIZED_STATUS = 401;
const HTTP_ERROR_STATUS = 404;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_ERROR_STATUS,
  HTTP_BAD_REQUST_STATUS,
  HTTP_CREATED_STATUS,
  HTTP_UNAUTHORIZED_STATUS,
};
